config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'home', to: 'pages#home', as: 'home'
  get 'about', to: 'pages#about', as:'about' 
  get 'about2', to: 'pages#about2', as:'about2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def about2
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
<%= link_to 'Home', home_path%>
</p>

app/views/pages/about2.html.erb
<h1>About my country</h1>



<p>
we strive to help you learn  git. Its our passion.
</p>

<p>
<%= link_to 'Home', home_path%>
</p>

app/views/pages/home.html.erb
<h1>Welcome top the web appliccation</h1>
<ul>
<li><%= link_to 'About', about_path%></li>
</ul>


<p>
We are really hopefull that its really healpfull
</p>


ul>
<li><%= link_to 'About2', about2_path%></li>
</ul>